### ISSUE TITLE
Implement 'maybe' type validator

### ISSUE THREAD

**Issue by mthadley** [metal/metal-state-validators#7]
Consider adding a `maybe` validator, since we currently don't have a good way to describe optional or conditional values.

You could use it like this:

``` js
import Types from 'metal-state-validators';

MyComponent.STATE = {
   someData: {
      validator: Types.maybe(Types.object)
   }
}
```

and this would warn if it was passed anything other than `null` or an `object`.

Inspired by `Maybe` and maybe-like data types in [Rust](https://doc.rust-lang.org/std/option/), [Elm](http://package.elm-lang.org/packages/elm-lang/core/4.0.1/Maybe), [Haskell](https://hackage.haskell.org/package/base-4.9.0.0/docs/Data-Maybe.html), and others. `null` would be operating as the `Nothing` or `None` type in this case.

**Comment by ethib137** [comment]
Should Types.maybe() also accept 'undefined'? 

I'm wondering since we often will do something like this.

``` javascript
let x;

if (y) {
    x = y;
} 

return <Component attr={x} />;
```

In the instance that the 'if' statement does not run, x will be 'undefined'. It seems like we should either be okay with letting maybe accept 'undefined', or we need to consistently declare variables like this: 

``` javascript
let x = null;
```

Does that sound about right, or am I missing something?

**Comment by bryceosterhaus** [comment]
Sounds reasonable to me. I just added an additional commit for undefined as well.

**Comment by mairatma** [comment]
https://github.com/metal/metal-state-validators/pull/8 was merged and the feature is available in version 0.1.2 :)

**Comment by mthadley** [comment]
We can handle that case, but there is something to be said for getting a warning for `undefined`. `null` and `undefined` are very similar but they mean different things (empty value vs there was never a value). I've always seen `null` as similar to empty string, but for any type.

Plus, if you think of a component as a function:

``` js
// myfunc(paramA, paramB, paramC) where paramB can be expected
// to sometimes "not be there".

myFunc(a, undefined, c)

// vs

myFunc(a, null ,c);
```

Either way, I'm fine with the change, but I just wanted to give my rationale for not including `undefined` initially.

**Comment by ethib137** [comment]
@mthadley I think I agree with you... My preference is actually that we don't initialize values equal to 'undefined' but rather initialize them set to 'null'. 

```
let x = null; // do this

let x; // not this
```

Then we don't need to let Types.maybe accept 'undefined'.

**Comment by mairatma** [comment]
I think undefined values make sense to be accepted in a function called `maybe`, and it can be annoying to have to write boilerplate like this for a case so common. I believe that most times it wouldn't be a problem to accept undefined as well, right? In cases where someone needs to treat undefined differently they can always do the check via `oneOfType` instead of `maybe`.

**Comment by mthadley** [comment]
I think that's why I can see it written either way. For example, it might be annoying to have to write this:

``` js
Person.STATE = {
  name: {
    validator: Types.string
  },

  title:  {
    validator: Types.maybe(Types.string)
  }
};

// ...

renderPerson(name, title = null) {
  return <Person name={name} title={title} />;
}

//...

<div>{renderPerson('mike')}</div>

// But then it could have been invoked like this, and we could
// omit the default parameter for `title`

<div>{renderPerson('mike', null)}</div>

```

In the above case if we allow `undefined`, we don't have to worry about any of that. However, maybe we miss a bug later because we forgot to pass a value.

I think throwing a warning for `undefined` leads to a more functional approach to things, but allowing `undefined` might map more cleanly to javascript practices in general.
